version: '3'

services:

  ab-magnus:
    build:
      context: .
      dockerfile: Dockerfile
    image: phonevox/ab-magnus
    ports:
    - "${EXPRESS_DOCKER_PORT:-7778}:${EXPRESS_PORT:-3000}"
    env_file:
    - .env
    container_name: ab-magnus
    restart: unless-stopped
    stdin_open: true
    tty: true
    depends_on:
    - redis-server
    volumes:
    - ./docker-logs/:/app/logs
    - ./docker-npm/:/app/logs

  redis-server:
    image: redis:6.2.14-alpine
    container_name: ab-redisserver
    command: redis-server --save 20 1 --loglevel warning --requirepass ${REDIS_PASSWORD?error}
    restart: always
    volumes: 
    - ./redis-data:/data
    ports:
    - '6379:6379'
    env_file:
    - .env